name: check-style

on:
  push:
    branches:
      - check_style

jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache NPM Modules
        id: cache-frontend-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-frontend-npm
        with:
          path: ./frontend/node_modules/
          key: cache-frontend-npm-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-frontend-npm.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: ./frontend
        
      - name: Check Frontend Style
        working-directory: ${{ github.workspace }}/frontend/
        run: npx prettier --check ./src/**/*.js

      # - name: Check Crawler Style
      #   uses: creyD/prettier_action@v4.3
      #   with:
      #     working_directory: ${{ github.workspace }}/crawler/
      #     dry: true
      #     github_token: ${{ github.token }}
      #     prettier_options: --check ./src/**/*.js
